// =====================================================================
// Pinewood Executive Operations Dashboard — DAX measures
// Paste each measure into Power BI Desktop (Modeling > New Measure).
// Every measure is explained in powerbi/README_POWERBI.md and the root README.
// Tables referenced are the Gold tables loaded from warehouse/pinewood.duckdb.
// =====================================================================

// ---- 1. Current occupancy percent -----------------------------------
// Latest available month's occupied units over total units, across the
// current filter context (community / region).
Current Occupancy % =
VAR LastMonth =
    CALCULATE ( MAX ( fact_occupancy_monthly[month_start] ), ALL ( dim_date ) )
RETURN
    DIVIDE (
        CALCULATE (
            SUM ( fact_occupancy_monthly[occupied_units] ),
            fact_occupancy_monthly[month_start] = LastMonth
        ),
        CALCULATE (
            SUM ( fact_occupancy_monthly[total_units] ),
            fact_occupancy_monthly[month_start] = LastMonth
        )
    )

// ---- 2. Year-over-year revenue growth percent -----------------------
// Revenue comes from fact_revenue_monthly (monthly_rate prorated by the days
// each lease was occupied in the month).
Revenue Amount =
SUM ( fact_revenue_monthly[revenue] )

YoY Revenue Growth % =
VAR CurrentRev = [Revenue Amount]
VAR PriorRev =
    CALCULATE ( [Revenue Amount], SAMEPERIODLASTYEAR ( dim_date[date] ) )
RETURN
    DIVIDE ( CurrentRev - PriorRev, PriorRev )
// NOTE: the sample data spans 2025-01..2025-06 only, so SAMEPERIODLASTYEAR
// returns blank (no 2024 rows). The pattern is correct; YoY lights up the
// moment a second year of data lands. For a populated period-over-period
// number on this dataset, see [Revenue MoM Growth %] below.

Revenue MoM Growth % =
VAR CurrentRev = [Revenue Amount]
VAR PriorRev = CALCULATE ( [Revenue Amount], PREVIOUSMONTH ( dim_date[date] ) )
RETURN
    DIVIDE ( CurrentRev - PriorRev, PriorRev )

// ---- 3. Average daily census for a selected date range --------------
// resident_days summed over the selection / number of days selected.
Average Daily Census =
DIVIDE (
    SUM ( fact_census_monthly[resident_days] ),
    DISTINCTCOUNT ( dim_date[date] )
)

// ---- 4. Move-out rate percent, trailing 90 days ---------------------
// Move-outs in the last 90 days over average census in the same window.
Move-Out Rate % (Trailing 90d) =
VAR MaxDate = MAX ( dim_date[date] )
VAR Window = DATESINPERIOD ( dim_date[date], MaxDate, -90, DAY )
VAR MoveOuts =
    CALCULATE ( COUNTROWS ( fact_moveouts ), fact_moveouts[move_out_date] IN Window )
VAR AvgCensus =
    CALCULATE ( [Average Daily Census], Window )
RETURN
    DIVIDE ( MoveOuts, AvgCensus )

// ---- 5. Incident rate per 100 resident-days -------------------------
Incident Rate per 100 Resident-Days =
DIVIDE (
    COUNTROWS ( fact_incidents ) * 100,
    SUM ( fact_census_monthly[resident_days] )
)

// ---- 6. Time-intelligence beyond YoY: Rolling 90-day incidents ------
// A trailing-90-day count that moves with the selected date — useful for
// spotting recent spikes the monthly view hides.
Incidents Rolling 90d =
CALCULATE (
    COUNTROWS ( fact_incidents ),
    DATESINPERIOD ( dim_date[date], MAX ( dim_date[date] ), -90, DAY )
)

// Also provided: Month-to-date census.
Census MTD =
TOTALMTD ( SUM ( fact_census_monthly[resident_days] ), dim_date[date] )

// ---- 7. CALCULATE with context transition ---------------------------
// "Average occupancy across communities" — we need the occupancy % computed
// PER community (a row context over dim_community) and then averaged. AVERAGEX
// establishes a row context per community; CALCULATE inside the iterator forces
// context transition, turning that row into an equivalent filter on
// fact_occupancy_monthly so [Current Occupancy %] is evaluated for THAT
// community only. Without context transition the measure would ignore the row
// and return the same all-up number for every community.
Avg Community Occupancy % =
AVERAGEX (
    VALUES ( dim_community[community_id] ),
    CALCULATE ( [Current Occupancy %] )   // context transition here
)

// ---- Supporting measures used on the dashboard ----------------------
Total Incidents = COUNTROWS ( fact_incidents )

Avg Review Rating = AVERAGE ( fact_reviews[rating] )

Labor Cost per Resident-Day =
DIVIDE (
    SUM ( fact_labor_monthly[labor_cost] ),
    SUM ( fact_census_monthly[resident_days] )
)

Occupied Units = SUM ( fact_occupancy_monthly[occupied_units] )
Total Units    = SUM ( fact_occupancy_monthly[total_units] )
